smc: calculate investing
lamtt2403/EZC pull request #3
Opened 2022-03-17 05:31 UTC by lamtt2403

2022-03-17 07:12 UTC, Zergity requested changes
1. critical calculation mistake: `limitAmount`
2. missing feature: cliff time
3. missing events
4. missing js feature test for time wrapping test
5. naming semantic: Vesting, not investment (they have total different meaning)

2022-03-17 07:12 UTC, Zergity commented on contracts/CalculateInvesting.sol
> +    address payable public owner;
`owner` don't have to be `payable`

2022-03-17 07:12 UTC, Zergity commented on contracts/CalculateInvesting.sol
> +        uint totalEZC;
advanced math and storage optimization: totalEZC, ezcPerDay, startTime, and numberWithdrawed can be redesigned into only 3 uints

2022-03-17 07:12 UTC, Zergity commented on contracts/CalculateInvesting.sol
> +        investments[_investor] = Investment({
state checks: investment exists, totalEZC > 0, ezcPerDay > 0, etc.

2022-03-17 07:12 UTC, Zergity commented on contracts/CalculateInvesting.sol
> +        uint currentAmount = investment.ezcPerDay * numDays;
wrong calculation, this allows user to withdraw all totalEZC amount without waiting for vesting time

2022-03-17 17:06 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +        uint numDays = (block.timestamp - investment.startTime) / 60 / 60 / 24;
If you use seconds to calculate then you will have to convert ezcPerDay to ezcPerSecond. Is there any other way?

2022-03-17 17:25 UTC, lamtt2403 commented
> 1. critical calculation mistake: `limitAmount`
> 2. missing feature: cliff time
> 3. missing events
> 4. missing js feature test for time wrapping test
> 5. naming semantic: Vesting, not investment (they have total different meaning)

2022-03-17 17:25 UTC, closed without merging

2022-03-17 17:32 UTC, lamtt2403 commented
I just created a new `[pull request](https://github.com/lamtt2403/EZC/pull/2/files)` to update your comments. However, I have not completed the memory optimization (totalEZC, ezcPerDay, startTime, and numberWithdrawed can be redesigned into only 3 uints) yet, I will update later

2022-03-18 01:44 UTC, Zergity commented
> I just created a new [pull request](https://github.com/lamtt2403/EZC/pull/2/files) to update your comments. However, I have not completed the memory optimization (totalEZC, ezcPerDay, startTime, and numberWithdrawed can be redesigned into only 3 uints) yet, I will update later

don't do this next time, when you have comment on a PR, you fix it (or discuss it) and push more commit on the PR branch to continue the review

2022-03-18 05:33 UTC, lamtt2403 commented
> > I just created a new [pull request](https://github.com/lamtt2403/EZC/pull/2/files) to update your comments. However, I have not completed the memory optimization (totalEZC, ezcPerDay, startTime, and numberWithdrawed can be redesigned into only 3 uints) yet, I will update later
> 
> don't do this next time, when you have comments on a PR, you fix it (or discuss it) and push more commits on the PR branch to continue the review

Ok, I got it

2022-03-18 09:52 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +        address investor;
https://github.com/lamtt2403/EZC/commit/1a9c441525ccb40a9e981b623a6f976342c6b378

2022-03-18 09:54 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +    function changeLock(address _investor) public onlyOwner {
https://github.com/lamtt2403/EZC/commit/2ae58bf2a6419caa0ce3a26c5ecfe7a4f2ad0e7d

2022-03-18 09:59 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +        uint limitAmount = investment.totalEZC - investment.numberWithdrawed;
update: calculate using SafeMath [here](https://github.com/lamtt2403/EZC/commit/2fbf2b1d391ad082be73f13a6955a9a5c7b8120a)

2022-03-18 10:01 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +    address payable public owner;
remove: declared payable [here](https://github.com/lamtt2403/EZC/commit/fb5763f146b340d307fb11249cb1003cc5a6fef9)

2022-03-18 10:15 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +        investments[_investor] = Investment({
state check: https://github.com/lamtt2403/EZC/commit/b3c6ed26af3fae364c48cfc5e43c052bf5e469e3

2022-03-18 10:28 UTC, lamtt2403 commented on contracts/CalculateInvesting.sol
> +        uint numDays = (block.timestamp - investment.startTime) / 60 / 60 / 24;
According to the first function, the input is EZC vesting per day. so i will calculate by number days

2022-03-19 14:37 UTC, lamtt2403 commented
> 1. critical calculation mistake: `limitAmount`
> 2. missing feature: cliff time
> 3. missing events
> 4. missing js feature test for time wrapping test
> 5. naming semantic: Vesting, not investment (they have total different meaning)

cliff time is not mentioned in the requirement